class Codes:
    idToStr = {
        0: 'Bâtiments',
        1: 'Mine de Métal',
        2: 'Mine de Cristal',
        3: 'Synthétiseur de Deutérium',
        4: 'Centrale éléctrique Solaire',
        6: 'Université',
        12: 'Centrale de fusion',
        14: 'Usine de Robots',
        15: 'Usine de Nanites',
        21: 'Chantier Spatial',
        22: 'Hangar de Métal',
        23: 'Hangar de Cristal',
        24: 'Réservoir de Deutérium',
        31: 'Laboratoire de Recherche',
        33: 'Terraformeur',
        34: 'Dépôt d\'Alliance',
        44: 'Silo de Missiles',
        40: 'Bâtiments lunaires',
        41: 'Base Lunaire',
        42: 'Phalange de capteurs',
        43: 'Porte de Saut',
        100: 'Recherche',
        106: 'Technologie d\'Espionnage',
        108: 'Technologie Ordinateur',
        109: 'Technologie Armes',
        110: 'Technologie Bouclier',
        111: 'Technologie Blindage',
        113: 'Technologie Énergie',
        114: 'Technologie Hyperespace',
        115: 'Réacteur à Combustion',
        117: 'Réacteur à Impulsion',
        118: 'Propulsion Hyperespace',
        120: 'Technologie Laser',
        121: 'Technologie Ion',
        122: 'Technologie Plasma',
        123: 'Réseau de Recherche Intergalactique',
        124: 'Astrophysique',
        131: 'Optimisation de la production en Métal',
        132: 'Optimisation de la production en Cristal',
        133: 'Optimisation de la production en Deutérium',
        199: 'Technologie Graviton',
        200: 'Vaisseaux',
        202: 'Petit transporteur',
        203: 'Grand transporteur',
        204: 'Chasseur léger',
        205: 'Chasseur lourd',
        206: 'Croiseur',
        207: 'Vaisseau de bataille',
        208: 'Vaisseau de colonisation',
        209: 'Recycleur',
        210: 'Sonde d\'espionnage',
        211: 'Bombardier',
        212: 'Satellite solaire',
        213: 'Destructeur',
        214: 'Étoile de la mort',
        215: 'Traqueur',
        216: 'Lune Noire',
        217: 'Transporteur ultime',
        218: 'Avatar',
        219: 'Recycleur ultime',
        220: 'Collectionneur',
        400: 'Systèmes de Défense',
        401: 'Lanceur de missiles',
        402: 'Canon laser léger',
        403: 'Canon laser puissant',
        404: 'Canon de Gauss',
        405: 'Artillerie à Ions',
        406: 'Lanceur de Plasma',
        407: 'Petit Bouclier',
        408: 'Grand Bouclier',
        409: 'Dôme de Protection',
        410: 'Canon à Gravitons',
        411: 'Plateforme Orbitale',
        500: 'Missiles',
        502: 'Missiles d\'Interception',
        503: 'Missiles Interplanétaires',
        600: 'Officiers',
        601: 'Géologue',
        602: 'Amiral',
        603: 'Ingénieur',
        604: 'Technocrate',
        605: 'Constructeur',
        606: 'Scientifique',
        607: 'Expert du stockage',
        608: 'Ministre de la Défense',
        609: 'Gardien',
        610: 'Espion',
        611: 'Commandant',
        612: 'Destructeur',
        613: 'Général',
        614: 'Conquérant',
        615: 'Empereur',
        700: 'Premium Optimisations',
        701: 'Optimisation des Armes',
        702: 'Optimisation des Boucliers',
        703: 'Optimisation des Constructions',
        704: 'Optimisation des Ressources',
        705: 'Optimisation de l\'Energie',
        706: 'Optimisation de la Recherche',
        707: 'Upgrade Flotte',
        900: 'Ressources',
        901: 'Métal',
        902: 'Crystal',
        903: 'Deuterium',
        911: 'Énergie',
        921: 'Matiére Noir'
    }
    strToId = {string: id for id, string in idToStr.items()}